services:
    server:
        container_name: server
        build:
            dockerfile: ./Dockerfile
        volumes:
            - /var/www/html/vendor
            - .:/var/www/html
        networks:
            - swoole
        ports:
            - "8080:80"
networks:
    swoole:
        driver: bridge
